### ISSUE TITLE
WebDav sync replaces existing files with zero byte copies

### ISSUE THREAD

**Issue by ashleysommer** [redsolver/noteless#26]
Hi,
I know WebDav sync is considered experimental, and I know it says not to use it on important files.

I wanted to test if it would work for my workflow. I have a owncloud store with an existing "notable" directory, with approx 30 notes in the notes directory.

When I enable WebDav sync in this app, and point the location to my owncloud store's webdav interface, it shows the normal "syncing with WebDav" message, but none of my existing notes from owncloud appears in the app.

When I check my owncloud web interface, I see the android app has uploaded all of the Tutorial files (as expected) but it has also replaced all of my existing notes with zero-byte versions (Truncated them?).

Its easy enough to roll-back the files to the previous state using the owncloud web interface, but I'd prefer if I didn't have to do that.

Is it a bug that it does that, or is that expected in this Experimental state?

**Comment by redsolver** [comment]
Thank you for the feedback!
I tested the webdav sync with my NextCloud instance on different devices and something like this should not happen.
I will add an export logs feature for the sync in the next release, so I can analyze the issue better.

For now, it would be helpful if you could tell me the timezone of your owncloud instance.

**Comment by redsolver** [comment]
To better understand the issue:
1. Please update to Alpha 0.1.8
2. Enable "Create sync logfile" in options
3. Try to sync your files
4. Send the content of the `[DEBUG] Sync` file

Thank you!

**Comment by ashleysommer** [comment]
Hi,
I just updated to 0.1.8, enabled sync logfile, and recreated the issue.

Heres the log file:
https://gist.github.com/ashleysommer/6a6d3ad10c3eef76e44cef316c12be68

Some context:
The owncloud server I'm using is operated by a research network in Australia, they appear to be using OwnCloud v10.1.1. The timezone they are located in is Australian Eastern Daylight Savings time (GMT +11) but my timezone is Australian Eastern Standard Time (GMT +10) (we don't observe daylight savings) so the Server is 1 hour ahead of the Client. But I don't think that matters because the log file shows times in GMT/UTC.

When I recreated the bug this time, the exact same thing weird things happened.
1) All of the Tutorial files shipped with the App were uploaded, replacing those which existed on the server (I guess because the ones in the App are newer).
2) None of the existing files on the server were downloaded to the app.
3) When I check my owncloud interface, all files (the new Tutorial files uploaded, and my existing notes) show size 0 bytes and contents are empty.
4) All other PCs which are set to sync from that server directory also get the zero byte files synced down replacing the local files.


Some interesting things I see in the log file:
1) Filenames containing Emojis always say "Does not exist on the server" even when they do. I think this is because OwnCloud strips the emojis out of the filenames when the files are uploaded.
2) The sync procedure _does_ see my existing files on there, and marks them `File does nott exist locally -> DOWNLOAD` but never downloads them.

I know this is a super weird issue, I hope you're able to debug this.

**Comment by redsolver** [comment]
When downloading a file, the app simply sends a `GET` request to the server which should not change any state server-side.

The only thing I can imagine is that something with the OwnCloud instance could be wrong - but I've never seen something like this before.

It would be helpful if you could access the server-side logs, but I don't think that's possible.

**Comment by redsolver** [comment]
I decided to drop support for syncing notes directly via the app in the new release, because it's very hard to implement it right and there are a lot better apps for it which primary feature is synchronisation. Maybe someday it will return, but for now I recommend using an external data directory and using a third-party sync app for Android like [Syncthing](https://syncthing.net/) or FolderSync for other cloud services.

**Comment by ashleysommer** [comment]
Thanks for your work on this @redsolver 
I ended up going with the NextCloud sync app from the F-Droid app store, it does what I need, and seems to have compatibility with the older owncloud server the research network uses.
