### ISSUE TITLE
Performance optimization for preview

### ISSUE THREAD

**Issue by spiral6** [redsolver/noteless#28]
It seems like adding an image and/or a checkbox (which appears to be a rendered image rather than a HTML tag) causes the performance for the preview to drastically drop. 

This seems to be a prevalent issue with Flutter at the moment. Though it possibly has been fixed fairly recently. https://github.com/brendan-duncan/image/issues/104

There's also a non-native option.
https://pub.dev/packages/flutter_image_compress

My suggestion is either to cache or compress (in memory) the displayed image through some optimization, as well as replace the checkbox with an actual HTML checkbox.

**Comment by redsolver** [comment]
The preview is implemented with a fully native webview, so it should have nothing to do with Flutter. I tried some notes with and without images and could not find any major differences in performance. 

Which is your default browser?

**Comment by spiral6** [comment]
Google Chrome on Android.

**Comment by redsolver** [comment]
Please try the latest release: https://github.com/redsolver/noteless/releases/tag/v1.1.0

It makes checkboxes toggleable and also contains some performance improvements from Flutter. Please re-open this issue if the problem still persists. Thank you!
