### ISSUE TITLE
Location doesn't update on main settings 

### ISSUE THREAD

**Issue by genericmoniker** [redsolver/noteless#30]
Version 0.1.8

**Steps**
1. Settings > Location
2. Pick a new note location using the file browser

**Expected** - The "Location" field on the settings screen updates with the newly chosen location.
**Actual** - The "Location" field retains its old value. The value *does* actually update internally but the display doesn't until leaving settings and returning. This caused me to think it wasn't working until exiting the settings to discover the new location had been applied.

BTW - Thanks for making this!

**Comment by redsolver** [comment]
Thank you for the feedback!

Before updating the UI, every note in the new location is read - this obviously takes longer with more notes.
I will add a progress dialog to communicate this behavior in the next release.
