### ISSUE TITLE
invalid YAML frontmatter

### ISSUE THREAD

**Issue by madeindjs** [redsolver/noteless#33]
I think this is due to missing title but Notable handle this and fallback to filename. Also I can't even open the note.

![Screenshot_20200707-230827](https://user-images.githubusercontent.com/11815139/86843850-74362b80-c0a7-11ea-8932-982b8340c063.jpg)

**Comment by redsolver** [comment]
Thank you for the report! Currently the app expects at least a title and a created/modified date. Your error is caused most likely by the missing dates. I will add some code to fallback to the actual file's metadata if it's missing in the next release (tomorrow). The next release will also make more clear that the ERROR Tiles are actually not files or notes.

**Comment by redsolver** [comment]
Just added the fallback handling in the new release [Alpha 0.3.0](https://github.com/redsolver/noteless/releases/tag/v0.3.0).

**Comment by redsolver** [comment]
@madeindjs Could you please try the latest [Alpha 0.3.1](https://github.com/redsolver/noteless/releases/tag/v0.3.1) and confirm that it works?

**Comment by madeindjs** [comment]
Yes it works. Thank you very much.

But I Still have an issue with this YAML frontmatter (which is valid):

```
---
title: Security
tags:
  - node
emoji: 👮‍♂️
---

Maybe this is due to emoji or mutline array syntax. 
```

**Comment by redsolver** [comment]
The yaml parser used by this app doesn't support emojis yet (https://github.com/dart-lang/yaml/issues/53). A possible workaround is to use the escape sequence `\U0001F46E‍` instead of the emoji in the yaml.

**Comment by madeindjs** [comment]
Ok So I think I can close issue for now. Thank you again.
