### ISSUE TITLE
Load files without header

### ISSUE THREAD

**Issue by janteau** [redsolver/noteless#34]
I noticed that markdown files placed in the notes directory are not recognized by Noteless without the proper header:
```
---
tags:
title:
created:
modified:
---
```
Many of my markdown files I've created manually with a text editor on a PC.  Would it be possible to open these files without the header being present, and maybe only add it if changes are made in Noteless?

**Comment by redsolver** [comment]
Are you using the latest [Alpha 0.3.0](https://github.com/redsolver/noteless/releases/tag/v0.3.0)? I just added fallback handling for missing header data or keys in this release.

**Comment by janteau** [comment]
I was not - I just downloaded it yesterday and between the time of my downloading and the time I made the issue I didn't see you had released a new version.

I tried Alpha 0.3.0.  It now sees the files without the header information, but when I try and open them I just see the "progress" moving colors at the top of the screen like it's trying to them.

![Screenshot_20200709-162012_Noteless](https://user-images.githubusercontent.com/32575346/87087140-1712b500-c222-11ea-9594-7ad83b042032.png)

**Comment by redsolver** [comment]
Thank you for the report, it should now finally work in [Alpha 0.3.1](https://github.com/redsolver/noteless/releases/tag/v0.3.1)

**Comment by janteau** [comment]
Alpha 0.3.1 works.  Thanks!

**Comment by mortezadadgar** [comment]
@redsolver sorry for commenting on a closed issue, I have a bunch of markdown files on my PC when I try to sync with phone and select the notes folder as external storage, noteless list all my mardown files titled as "null" and If i try to edit one of them the markdown files get renamed to my header1 and noteless now recognize my notes, would u just make this app fallback to header1 for titles in case of no metadata (title, modified, etc) is available

**Comment by redsolver** [comment]
@mortezadadgar Try enabling "Enable Dendron support" in the Experimental Settings

**Comment by mortezadadgar** [comment]
> @mortezadadgar Try enabling "Enable Dendron support" in the Experimental Settings

Raw data
![Screenshot_20210728-151557_Material_Files](https://user-images.githubusercontent.com/27911493/127311527-c680a158-85a8-4663-a790-8aa6181163fa.png)

Noteless
![Screenshot_20210728-151534_Noteless](https://user-images.githubusercontent.com/27911493/127311636-079b7191-17ea-44f3-9b14-ef7262b46033.png)

With enabled dendron support I don't get any title even after editing the file
