### ISSUE TITLE
[Enhancement] Preview Checkboxes

### ISSUE THREAD

**Issue by tongong** [redsolver/noteless#37]
It would be really cool, if you could check and uncheck markdown checkboxes directly in the preview window, just like in the notable app.

**Comment by redsolver** [comment]
Will be added in Version 1.1 today

**Comment by redsolver** [comment]
Added in https://github.com/redsolver/noteless/releases/tag/v1.1.0

Please let me know if everything works as expected, thank you!

**Comment by tongong** [comment]
It works now. Thank you so much!
