### ISSUE TITLE
Local links to notes do not seem to work

### ISSUE THREAD

**Issue by Vetii** [redsolver/noteless#38]
I tried to create two notes, one named A and one named B.

If I create a local link from B to A, by typing `[[A]]` and enter display mode, then `[[A]]` is not turned into a link.

**Comment by redsolver** [comment]
Working on it, should get into the 1.1 Release today. Just added Syntax Highlighting: 
![image](https://user-images.githubusercontent.com/30355444/90801126-cbb9ef00-e315-11ea-8ccc-919b100f7885.png)

**Comment by redsolver** [comment]
Added in https://github.com/redsolver/noteless/releases/tag/v1.1.0

Please let me know if everything works as expected, thank you!

**Comment by redsolver** [comment]
@Vetii Could you please confirm that it's working now?

**Comment by Vetii** [comment]
I tried on the app, and it seems to work, thanks! Closing the issue.
