### ISSUE TITLE
Option for non-strict line breaks

### ISSUE THREAD

**Issue by NomarCub** [redsolver/noteless#39]
Single line breaks don't show in preview mode in accordance with the Markdown specs. Other editors don't always work this way, and a single line break is enough to place something in the next line in preview mode. It would be nice to have an option to have it work either way.

**Comment by redsolver** [comment]
So this is the markdown spec:

---

```
line1
line2
```
![Screenshot_20200824_213635](https://user-images.githubusercontent.com/30355444/91088337-1b6c2380-e652-11ea-96c5-ab7c0c13ad1e.png)

---

```
line1 \
line2
```
![Screenshot_20200824_213712](https://user-images.githubusercontent.com/30355444/91088340-1c9d5080-e652-11ea-90de-98f5c1552aa1.png)

---

```
line1

line2
```
![Screenshot_20200824_213734](https://user-images.githubusercontent.com/30355444/91088341-1c9d5080-e652-11ea-9a26-c50deccf5276.png)

---

And you want the following behaviour as an option?

---

```
line1
line2
```
![Screenshot_20200824_213712](https://user-images.githubusercontent.com/30355444/91088340-1c9d5080-e652-11ea-90de-98f5c1552aa1.png)

**Comment by NomarCub** [comment]
Yes, exactly.
Desktop apps, such as Notable, Boostnote, Zettlr, Marktext, Obsidian etc. work that way, so I'd like to get away with not reformatting all my notes on mobile as well.

**Comment by redsolver** [comment]
Added the option in Version 1.2.0 (https://github.com/redsolver/noteless/releases/tag/v1.2.0). You need to enable it in the Settings under `Enable single line break syntax`.

Please let me know if everything works as expected, thank you!
