### ISSUE TITLE
Table borders

### ISSUE THREAD

**Issue by femto-code** [redsolver/noteless#40]
Hi, I recently came across this app - and it is really nice!

I just checked this [markdown file](https://github.com/marktext/marktext/blob/develop/docs/MARKDOWN_SYNTAX.md) _(from the docs of another Markdown editor for PC)_ in your app (on Android) and found that it would be helpful to have proper table borders.

With this being fixed, I will use this app for writing/viewing my documents for studying. Thank you for this **feature-rich** app with generous capabilities of managing files **without** a proprietary sync server or closed-source data format.

**Comment by redsolver** [comment]
Added in https://github.com/redsolver/noteless/releases/tag/v1.2.1 :tada:

**Comment by femto-code** [comment]
> Added in https://github.com/redsolver/noteless/releases/tag/v1.2.1 🎉

Looks great, thank you for instantly working on it! 🎉 👍 
Closing this.
