### ISSUE TITLE
Small scrolling improvement

### ISSUE THREAD

**Issue by femto-code** [redsolver/noteless#43]
I just have another suggestion concerning the scrolling behavior.
If there is a `<pre>` section in a Markdown notes file, which is wider than the current devices' screen, then it appears a horizontal scrollbar for the whole note file. In fact, this disturbs sometimes when you accidentally scroll horizontally but just want to scroll the document vertically.
My suggestion would be: Making a `<pre>` section with following style rules would result in a scrollable area **only** for this part of the document.
```css
pre {
  max-width: 100%;
  overflow-x: scroll;
}
```
Would this be possible? Thank you in advance!

**Comment by redsolver** [comment]
Added in https://github.com/redsolver/noteless/releases/tag/v1.2.1

**Comment by femto-code** [comment]
> Added in https://github.com/redsolver/noteless/releases/tag/v1.2.1

Just installed your latest version `v1.2.1` and it works perfectly, thank you for your instant work on this - just great!
Closing this.
