### ISSUE TITLE
Notebooks / Tutorials / Basic / Intermediate / Advanced tags remain

### ISSUE THREAD

**Issue by spassvogel** [redsolver/noteless#71]
I've deleted the tutorial md files but the tags Notebooks / Tutorials / Basic / Intermediate and Advanced are still there. Each with 0 notes associated with it. How to remove these?

This is on Android btw

**Comment by redsolver** [comment]
Simply restart the app.

**Comment by spassvogel** [comment]
That did the trick, thanks!
