### ISSUE TITLE
Blocked from installing by Google play protect.

### ISSUE THREAD

**Issue by Norgus** [redsolver/noteless#75]
I tried to install the app but received a threatening sounding warning from the Google play protect thing suggesting the app might be malware.

I'm not an Android developer so not really sure if this is something you can remedy or not.

Fwiw I was installing from FDroid.

**Comment by redsolver** [comment]
hmm the version on F-Droid is compiled directly from the source code, so it should be 100% clean.
I also just uploaded the APK file from Noteless on F-Droid to VirusTotal and it confirmed that there is no malware: https://www.virustotal.com/gui/file/760d8ca0c073943829353fd423ef2b9009ec65489e9c95d645fc54fc7cff21f1/detection
