### ISSUE TITLE
Scrolling in formatted notes is choppy

### ISSUE THREAD

**Issue by mariobrostech** [redsolver/noteless#79]
Hi,

When browsing a note in the mode where the switch at the top-right of the screen is enabled (to enable rich text formatting), scrolling in the app becomes jittery. Is there any way this can be improved to be as smooth as scrolling in the unformatted mode?

Thanks in advance!

**Comment by redsolver** [comment]
Noteless uses a WebView to render formatted notes which can result in bad performance. The WebView is used to support advanced features like math equations or graphs. Maybe I will add a faster formatted note mode soon, some ideas for this were discussed in #45

**Comment by mariobrostech** [comment]
Ok, I'll close this issue to consolidate things and keep all relevant discussions in #45. Thanks again for the help!
